# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-02 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['routine', 'starting_age', 'question_text']},
        ),
        migrations.AddField(
            model_name='routine',
            name='number',
            field=models.PositiveIntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
