# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-29 01:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw', models.DecimalField(decimal_places=2, max_digits=4)),
                ('dev', models.DecimalField(decimal_places=2, max_digits=4)),
                ('func', models.DecimalField(decimal_places=2, max_digits=4)),
                ('out', models.DecimalField(decimal_places=2, max_digits=4)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='developmentaldomain',
            name='choice',
            field=models.CharField(choices=[('A', 'A = adaptive'), ('CG', 'CG = cognitive'), ('CM', 'CM = communication'), ('M', 'M = motor'), ('S', 'S = social')], max_length=2),
        ),
        migrations.AlterField(
            model_name='functionaldomain',
            name='choice',
            field=models.CharField(choices=[('E', 'E = engagement'), ('I', 'I = independence'), ('S', 'S = social relationships')], max_length=1),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='choice',
            field=models.CharField(choices=[('S', 'S = positive social relations'), ('K', 'K = acquiring and using knowledge and skills'), ('A', 'A = taking action to meet needs')], max_length=1),
        ),
    ]
