# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-30 01:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20180329_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developmentaldomain',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dev', to='survey.Question'),
        ),
        migrations.AlterField(
            model_name='functionaldomain',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='func', to='survey.Question'),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='out', to='survey.Question'),
        ),
    ]
