# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-07 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20180402_1643'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Child',
            new_name='Profile',
        ),
        migrations.AlterField(
            model_name='answer',
            name='rating',
            field=models.IntegerField(choices=[(1, 'Not yet'), (2, 'Sometimes'), (3, 'Often/Beyond')], default=1),
        ),
    ]
