# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-30 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_auto_20180330_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='section',
            field=models.IntegerField(choices=[(1, 'Waking Up'), (2, 'Meal Times'), (3, 'Getting Dressed'), (4, 'Toileting/Diaper'), (5, 'Outings (Going Out'), (6, 'Play Time With Others'), (7, 'Play Time by Him or Herself'), (8, 'Nap Time'), (9, 'Bath Time'), (10, 'Hanging Out Time (including TV & Books'), (11, 'Grocery Shopping'), (12, 'Outside Time'), (13, 'Bedtime'), (14, 'Transition Time')]),
        ),
        migrations.AlterUniqueTogether(
            name='developmentaldomain',
            unique_together=set([('question', 'choice')]),
        ),
        migrations.AlterUniqueTogether(
            name='functionaldomain',
            unique_together=set([('question', 'choice')]),
        ),
        migrations.AlterUniqueTogether(
            name='outcome',
            unique_together=set([('question', 'choice')]),
        ),
    ]
