# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-30 14:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_auto_20180330_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.IntegerField(choices=[(1, 'Waking Up'), (2, 'Meal Times'), (3, 'Getting Dressed'), (4, 'Toileting/Diaper'), (5, 'Outings (Going Out'), (6, 'Play Time With Others'), (7, 'Play Time by Him or Herself'), (8, 'Nap Time'), (9, 'Bath Time'), (10, 'Hanging Out Time (including TV & Books'), (11, 'Grocery Shopping'), (12, 'Outside Time'), (13, 'Bedtime'), (14, 'Transition Time')])),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='section',
        ),
        migrations.AddField(
            model_name='routine',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routine', to='survey.Question'),
        ),
        migrations.AlterUniqueTogether(
            name='routine',
            unique_together=set([('question', 'choice')]),
        ),
    ]
