# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-13 16:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_auto_20180408_0134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='dev',
            new_name='score_age',
        ),
        migrations.RenameField(
            model_name='score',
            old_name='func',
            new_name='score_full',
        ),
        migrations.RemoveField(
            model_name='score',
            name='out',
        ),
        migrations.RemoveField(
            model_name='score',
            name='raw',
        ),
        migrations.AddField(
            model_name='profile',
            name='last_submit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='submit_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='score',
            name='routine',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='survey.Routine'),
            preserve_default=False,
        ),
    ]
