# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-13 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0010_auto_20180412_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_submit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='submit_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
