# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-14 22:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0013_merge_20180414_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email_confirmed',
        ),
    ]
