# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-16 08:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0016_auto_20180416_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
