# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-19 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0017_archive_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='code',
            field=models.CharField(default='aw', max_length=5, unique=True),
            preserve_default=False,
        ),
    ]
